services:
  test-postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_admin_db
    ports:
      - '5433:5432'
    networks:
      - test-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  test-frontend-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test_frontend_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3307:3306'
    networks:
      - test-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5

  test-redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - test-network

networks:
  test-network:
    name: test-network
    driver: bridge
